config/routes.rb
RenascerProject::Application.routes.draw do
  resources :cities

  resources :states

  resources :type_addresses

  resources :people do
    resources :addresses
  end

  devise_for :users

  get "welcome/index", as: "welcome"
  root to: 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :birthday, :email, :fathers_name, :federal_id, :mothers_name, :name, :regional_id
  has_many :addresses
  accepts_nested_attributes_for :addresses
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_addr_form.html.erb
<%= form_for [@person, @person.addresses.build] do |f| %>
  <tr>
    <td><%= f.text_field :street%></td>
	  <td><%= f.text_field :number%></td>
      <td><%= f.text_field :complement%></td>
	  <td><%= f.submit %></td>
	  <td></td>
  </tr>
<% end %>

app/views/people/_addr_list.html.erb
	<%= @person.addresses.each do |addr| %>
	  <tr>
	  	<td><%= addr.street %></td>
	  	<td><%= addr.number %></td>
	  	<td><%= addr.complement %></td>
	  </tr>
	<% end %>

app/views/people/_form.html.erb
<%= simple_form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :federal_id %>
  <%= f.input :regional_id %>
  <%= f.input :birthday %>
  <%= f.input :email %>
  <%= f.input :mothers_name %>
  <%= f.input :fathers_name %>
  <%= f.simple_fields_for :addresses do |addr| %>
    <%= addr.input :street %>
    <%= addr.input :number %>
    <%= addr.input :complement %>
  <% end %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="container"> 
  <%= render 'layouts/messages' %>
</div>  
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:birthday) %></th>
      <th><%= model_class.human_attribute_name(:mothers_name) %></th>
      <th><%= model_class.human_attribute_name(:fathers_name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= person.name %></td>
        <td><%= person.birthday %></td>
        <td><%= person.mothers_name %></td>
        <td><%= person.fathers_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div> 
  <%= link_to t('new', :default => t("helpers.links.new")),
              new_person_path,
              :class => 'btn btn-primary' %>
  <%= link_to t('Cancel'), :back, :class => 'btn btn-danger'%>
</div>

app/views/people/new.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = Person -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:federal_id) %>:</strong></dt>
  <dd><%= @person.federal_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:regional_id) %>:</strong></dt>
  <dd><%= @person.regional_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birthday) %>:</strong></dt>
  <dd><%= @person.birthday %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @person.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mothers_name) %>:</strong></dt>
  <dd><%= @person.mothers_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fathers_name) %>:</strong></dt>
  <dd><%= @person.fathers_name %></dd>
</dl>
<table class="table table-striped"> 
	<thead>
	<caption>Addresses</caption>
	<tr>
		<th>Street</th>
	    <th>Number</th>
	    <th>Complement</th>
	    <th></th>
	    <th></th>
	</tr>
	</thead>
	<tbody id="addr_listing">
		<%= render :partial => 'addr_list'%>
	</tbody>
	<tbody id="insert_form">
		<%= render :partial => 'addr_form'%>
	</tbody>
</table>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>