config/routes.rb
RenascerProject::Application.routes.draw do
  resources :cities

  resources :states

  resources :type_addresses

  resources :people do
    resources :addresses
  end

  devise_for :users

  get "welcome/index", as: "welcome"
  root to: 'welcome#index'

end

app/controllers/type_addresses_controller.rb
class TypeAddressesController < ApplicationController
  # GET /type_addresses
  # GET /type_addresses.json
  def index
    @type_addresses = TypeAddress.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @type_addresses }
    end
  end

  # GET /type_addresses/1
  # GET /type_addresses/1.json
  def show
    @type_address = TypeAddress.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type_address }
    end
  end

  # GET /type_addresses/new
  # GET /type_addresses/new.json
  def new
    @type_address = TypeAddress.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type_address }
    end
  end

  # GET /type_addresses/1/edit
  def edit
    @type_address = TypeAddress.find(params[:id])
  end

  # POST /type_addresses
  # POST /type_addresses.json
  def create
    @type_address = TypeAddress.new(params[:type_address])

    respond_to do |format|
      if @type_address.save
        format.html { redirect_to @type_address, notice: 'Type address was successfully created.' }
        format.json { render json: @type_address, status: :created, location: @type_address }
      else
        format.html { render action: "new" }
        format.json { render json: @type_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /type_addresses/1
  # PUT /type_addresses/1.json
  def update
    @type_address = TypeAddress.find(params[:id])

    respond_to do |format|
      if @type_address.update_attributes(params[:type_address])
        format.html { redirect_to @type_address, notice: 'Type address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type_address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_addresses/1
  # DELETE /type_addresses/1.json
  def destroy
    @type_address = TypeAddress.find(params[:id])
    @type_address.destroy

    respond_to do |format|
      format.html { redirect_to type_addresses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/type_addresses_helper.rb
module TypeAddressesHelper
end

app/views/type_addresses/_form.html.erb
<%= simple_form_for @type_address, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :description %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                type_addresses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/type_addresses/edit.html.erb
<%- model_class = TypeAddress -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/type_addresses/index.html.erb
<%- model_class = TypeAddress -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:inactevated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @type_addresses.each do |type_address| %>
      <tr>
        <td><%= link_to type_address.id, type_address_path(type_address) %></td>
        <td><%= type_address.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_type_address_path(type_address), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      type_address_path(type_address),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_type_address_path,
            :class => 'btn btn-primary' %>
<%= link_to t('Cancel'), :back, :class => 'btn btn-danger'%>
</div>

app/views/type_addresses/new.html.erb
<%- model_class = TypeAddress -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/type_addresses/show.html.erb
<%- model_class = TypeAddress -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @type_address.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              type_addresses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_type_address_path(@type_address), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              type_address_path(@type_address),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>